### ISSUE TITLE
Dimensional Drawing for Shield

### ISSUE THREAD

**Issue by openTPM** [NextThingCo/CHIP-Hardware#1]
I do not see currently a dimensional drawing as a reference for shields.
Please see for example this image for the BeagleBone.
![](http://openlab.com.au/wp-content/uploads/2013/05/BeagleBone_Dimensions.png)

**Comment by openTPM** [comment]
On the forums milspect18 asked for these drawings as well.
http://bbs.nextthing.co/t/c-h-i-p-specs-hole-dimensions-accurate-board-dimensions/451

**Comment by blinkengus** [comment]
Holding off on publishing dimensional drawing PDF for ALPHA CHIP as it may not necessarily be compatible with CHIP v1.0, and seems like a good way to encourage people to jump the gun on mechanically-dependent designs. For the really determined, layer stack-up PDF is to scale, plus OrCAD source files are posted.
