### ISSUE TITLE
FM Pin/Capability of BT/WIFI modle?

### ISSUE THREAD

**Issue by mrlowalowa** [NextThingCo/CHIP-Hardware#3]
Hey,

I just checked out the data sheet of the Wifi/BT Chip and then the CHIP schematics.. Am I wrong or is this little thing capable of receiving FM (radio) signals? The FM_RX pin goes blind in the schematics. Can someone explain if this is FM Radio and why not implementing it? I would rather have a GPIO pin less and listen to some radio with my CHIP? :)

Just an idea. Or at least pull the pin out like the mic pin, so the ones who are interested do not have to wire to the "micro" pins of the BT/WIFI modul. Because out of my view it should be possible to control the FM section with the SPIO pins which are already implemented?

cheers from Germany

**Comment by blinkengus** [comment]
@mrlowalowa I think we've discussed this on the BBS, but the FM rx / antenna interface circuit needs to be added -- the module just provides a tuner. CHIP was just a little too tight on space to fit it.
