### ISSUE TITLE
.brd file openinig issue

### ISSUE THREAD

**Issue by AM7000000** [NextThingCo/CHIP-Hardware#5]
I tried to open .brd file in Eagle 7.5.0 Light Edition and this message will be appear, where is problem?

Loading C:/Users/Ten/Downloads/CHIP_v1_0_20151123.brd ...

Error:

line 1, column 1: Start tag expected.

**Comment by Flexshot** [comment]
Hi there,
CHIP was designed in OrCAD. You can download a lite version for free from
their website.

**Comment by AM7000000** [comment]
Thanks for reply, possible to convert to eagle or gerber? if yes how?

**Comment by cortices** [comment]
I had this same issue, I think it should be noted more obviously.

**Comment by foxharp** [comment]
The "lite" version of Orcad might be free, but a) it requires registration, and b) is Windows-only, AFAICT.  A PDF version of the .brd file would be spectacular -- it's hard to locate components without a map.

**Comment by blinkengus** [comment]
@foxharp what you're looking for has been available in the Stackup and Assembly PDFs.
@cortices it is noted in the readme that appears on the front page of the repo.
