### ISSUE TITLE
UART

### ISSUE THREAD

**Issue by tomtruitt** [NextThingCo/CHIP-Hardware#8]
Is any information available on CHIP's UART? Looking for 9 bit communications is CHIP capable?

**Comment by blinkengus** [comment]
9-bit mode is not supported through hardware UART. From the R8 user manual:

> The UART supports word lengths from five to eight bits, an optional parity bit and 1, 1.5 or 2 stop bits, and is fully programmable by an AMBA APB CPU interface. A 16-bit programmable baud rate generator and an 8-bit scratch register are included, together with separate transmit and receive FIFOs. Eight modem control lines and a diagnostic loop-back mode are provided.

https://github.com/NextThingCo/CHIP-Hardware/blob/master/CHIP%5Bv1_0%5D/CHIPv1_0-BOM-Datasheets/Allwinner%20R8%20User%20Manual%20V1.1.pdf
