### ISSUE TITLE
More complete datasheet?

### ISSUE THREAD

**Issue by foxharp** [NextThingCo/CHIP-Hardware#9]
Is there a more detailed, hardware-oriented datasheet?  I'm picturing block diagrams of the GPIO input pin subsystems, electrical characteristics that include minimum interrupt hold times, etc.

**Comment by blinkengus** [comment]
The R8 User manual is likely what you're looking for: https://github.com/NextThingCo/CHIP-Hardware/blob/master/CHIP%5Bv1_0%5D/CHIPv1_0-BOM-Datasheets/Allwinner%20R8%20User%20Manual%20V1.1.pdf
